// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9YnovxAXoGBcf43kw8Icpwa_Hzh64ixU',
    appId: '1:618550002568:web:018efa9b4464025a0d703d',
    messagingSenderId: '618550002568',
    projectId: 'kingjanlong-8d14d',
    authDomain: 'kingjanlong-8d14d.firebaseapp.com',
    storageBucket: 'kingjanlong-8d14d.firebasestorage.app',
    measurementId: 'G-1D1MBVJMLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIfwTlqkN2-j4e9NoShL3D2EUVb_TOcpU',
    appId: '1:618550002568:android:04cb3d1981922d070d703d',
    messagingSenderId: '618550002568',
    projectId: 'kingjanlong-8d14d',
    storageBucket: 'kingjanlong-8d14d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEdTPh9S_MzQqgxQVaKE04OlFESS_XcZM',
    appId: '1:618550002568:ios:b1774a7ec612de9d0d703d',
    messagingSenderId: '618550002568',
    projectId: 'kingjanlong-8d14d',
    storageBucket: 'kingjanlong-8d14d.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEdTPh9S_MzQqgxQVaKE04OlFESS_XcZM',
    appId: '1:618550002568:ios:b1774a7ec612de9d0d703d',
    messagingSenderId: '618550002568',
    projectId: 'kingjanlong-8d14d',
    storageBucket: 'kingjanlong-8d14d.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9YnovxAXoGBcf43kw8Icpwa_Hzh64ixU',
    appId: '1:618550002568:web:5d4a2b212b6690450d703d',
    messagingSenderId: '618550002568',
    projectId: 'kingjanlong-8d14d',
    authDomain: 'kingjanlong-8d14d.firebaseapp.com',
    storageBucket: 'kingjanlong-8d14d.firebasestorage.app',
    measurementId: 'G-WBLJKBGW0V',
  );
}

