// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtKpizurBDehpMe69-6K4DjDCVg8XnhU',
    appId: '1:315077496086:web:3516baee632b04de4d1437',
    messagingSenderId: '315077496086',
    projectId: 'anuphat-51164',
    authDomain: 'anuphat-51164.firebaseapp.com',
    storageBucket: 'anuphat-51164.firebasestorage.app',
    measurementId: 'G-PTRRJXS4XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp_qqrmb0ytAlHAuE1VYaypAD43Sp_c_8',
    appId: '1:315077496086:android:74255e87b3b541634d1437',
    messagingSenderId: '315077496086',
    projectId: 'anuphat-51164',
    storageBucket: 'anuphat-51164.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQChM2pDlm-Hhk7DRNwSErwNGnGSVHBlI',
    appId: '1:315077496086:ios:e24fb31cb60ec7184d1437',
    messagingSenderId: '315077496086',
    projectId: 'anuphat-51164',
    storageBucket: 'anuphat-51164.firebasestorage.app',
    iosBundleId: 'com.example.anuProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQChM2pDlm-Hhk7DRNwSErwNGnGSVHBlI',
    appId: '1:315077496086:ios:e24fb31cb60ec7184d1437',
    messagingSenderId: '315077496086',
    projectId: 'anuphat-51164',
    storageBucket: 'anuphat-51164.firebasestorage.app',
    iosBundleId: 'com.example.anuProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHtKpizurBDehpMe69-6K4DjDCVg8XnhU',
    appId: '1:315077496086:web:5ae24c74d9e1ee2b4d1437',
    messagingSenderId: '315077496086',
    projectId: 'anuphat-51164',
    authDomain: 'anuphat-51164.firebaseapp.com',
    storageBucket: 'anuphat-51164.firebasestorage.app',
    measurementId: 'G-CFTV54YQ8Q',
  );
}
